<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CandidatoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('candidatos')->insert([
            ['id' => '55', 'cargo_id' => '11', 'nome' => 'Dr Juan Garcia', 'partido' => 'PSD'],
            ['id' => '77', 'cargo_id' => '11', 'nome' => 'Dr Nil', 'partido' => 'Solidariedade'],
            ['id' => '11', 'cargo_id' => '11', 'nome' => 'Professor Gleivison', 'partido' => 'PP'],
            ['id' => '10', 'cargo_id' => '11', 'nome' => 'Reinaldinho', 'partido' => 'Republicanos'],
            ['id' => '21', 'cargo_id' => '11', 'nome' => 'Vinicius Mandato Coletivo PCB', 'partido' => 'PCB'],
            ['id' => '55555', 'cargo_id' => '13', 'nome' => 'Abel Gama', 'partido' => 'PSD'],
            ['id' => '22111', 'cargo_id' => '13', 'nome' => 'Abidias', 'partido' => 'PL'],
            ['id' => '36500', 'cargo_id' => '13', 'nome' => 'Adeildo Toque Toque', 'partido' => 'Agir'],
            ['id' => '22333', 'cargo_id' => '13', 'nome' => 'Ailson Slias', 'partido' => 'PL'],
            ['id' => '18123', 'cargo_id' => '13', 'nome' => 'Alberto Mendes', 'partido' => 'Rede'],
            ['id' => '55055', 'cargo_id' => '13', 'nome' => 'Alceu Moura', 'partido' => 'PSD'],
            ['id' => '40222', 'cargo_id' => '13', 'nome' => 'Alessandro Negó', 'partido' => 'PSB'],
            ['id' => '10211', 'cargo_id' => '13', 'nome' => 'Alicate', 'partido' => 'Republicanos'],
            ['id' => '36125', 'cargo_id' => '13', 'nome' => 'Amancio Papai Noel', 'partido' => 'Agir'],
            ['id' => '40333', 'cargo_id' => '13', 'nome' => 'Amanda Bombeira Civil', 'partido' => 'PSB'],
            ['id' => '11234', 'cargo_id' => '13', 'nome' => 'Amanda Monteiro', 'partido' => 'PP'],
            ['id' => '35003', 'cargo_id' => '13', 'nome' => 'Amelia', 'partido' => 'PMB'],
            ['id' => '11600', 'cargo_id' => '13', 'nome' => 'Amilton Pacheco', 'partido' => 'PP'],
            ['id' => '77123', 'cargo_id' => '13', 'nome' => 'Anderson Gandra', 'partido' => 'Solidariedade'],
            ['id' => '20000', 'cargo_id' => '13', 'nome' => 'Andre Pierobon', 'partido' => 'Pode'],
            ['id' => '11222', 'cargo_id' => '13', 'nome' => 'Angélica Cassanho', 'partido' => 'PP'],
            ['id' => '33111', 'cargo_id' => '13', 'nome' => 'Animal', 'partido' => 'Mobiliza'],
            ['id' => '11888', 'cargo_id' => '13', 'nome' => 'Anne Faria', 'partido' => 'PP'],
            ['id' => '20020', 'cargo_id' => '13', 'nome' => 'Arquimedes', 'partido' => 'Pode'],
            ['id' => '20800', 'cargo_id' => '13', 'nome' => 'Ary junior', 'partido' => 'Pode'],
            ['id' => '40111', 'cargo_id' => '13', 'nome' => 'Balbino', 'partido' => 'PSB'],
            ['id' => '18137', 'cargo_id' => '13', 'nome' => 'Barão nobre', 'partido' => 'Rede'],
            ['id' => '36036', 'cargo_id' => '13', 'nome' => 'Baratinha', 'partido' => 'Agir'],
            ['id' => '25193', 'cargo_id' => '13', 'nome' => 'Bibi bombeiro', 'partido' => 'PRD'],
            ['id' => '36789', 'cargo_id' => '13', 'nome' => 'Binho boiçucanga', 'partido' => 'Agir'],
            ['id' => '77007', 'cargo_id' => '13', 'nome' => 'Boni', 'partido' => 'Solidariedade'],
            ['id' => '30321', 'cargo_id' => '13', 'nome' => 'Brodinho', 'partido' => 'Novo'],
            ['id' => '15000', 'cargo_id' => '13', 'nome' => 'Caboclo', 'partido' => 'MDB'],
            ['id' => '43333', 'cargo_id' => '13', 'nome' => 'Cacique guarani', 'partido' => 'PV'],
            ['id' => '13000', 'cargo_id' => '13', 'nome' => 'Camila aquino', 'partido' => 'PT'],
            ['id' => '44123', 'cargo_id' => '13', 'nome' => 'Camila tereza', 'partido' => 'União'],
            ['id' => '12123', 'cargo_id' => '13', 'nome' => 'Capitão wellington', 'partido' => 'PDT'],
            ['id' => '18678', 'cargo_id' => '13', 'nome' => 'Chico macarrão', 'partido' => 'Rede'],
            ['id' => '40213', 'cargo_id' => '13', 'nome' => 'Cida paraiba', 'partido' => 'PSB'],
            ['id' => '70222', 'cargo_id' => '13', 'nome' => 'Cida pauba', 'partido' => 'Avante'],
            ['id' => '22224', 'cargo_id' => '13', 'nome' => 'Claudinha maresias', 'partido' => 'PL'],
            ['id' => '12000', 'cargo_id' => '13', 'nome' => 'Claudinho do trânsito', 'partido' => 'PDT'],
            ['id' => '12800', 'cargo_id' => '13', 'nome' => 'Claudio taxista', 'partido' => 'PDT'],
            ['id' => '25010', 'cargo_id' => '13', 'nome' => 'Coio', 'partido' => 'PRD'],
            ['id' => '22212', 'cargo_id' => '13', 'nome' => 'Comandante sergio ramos', 'partido' => 'PL'],
            ['id' => '50123', 'cargo_id' => '13', 'nome' => 'Cristiane maria', 'partido' => 'PSOL'],
            ['id' => '40112', 'cargo_id' => '13', 'nome' => 'Dani kihara', 'partido' => 'PSB'],
            ['id' => '25244', 'cargo_id' => '13', 'nome' => 'Daniel do morro', 'partido' => 'PRD'],
            ['id' => '11123', 'cargo_id' => '13', 'nome' => 'Daniel simões', 'partido' => 'PP'],
            ['id' => '10123', 'cargo_id' => '13', 'nome' => 'Daniel soares', 'partido' => 'Republicanos'],
            ['id' => '30222', 'cargo_id' => '13', 'nome' => 'Danúbia da integra', 'partido' => 'Novo'],
            ['id' => '30001', 'cargo_id' => '13', 'nome' => 'David nascimento', 'partido' => 'Novo'],
            ['id' => '40640', 'cargo_id' => '13', 'nome' => 'Dedinho', 'partido' => 'PSB'],
            ['id' => '36777', 'cargo_id' => '13', 'nome' => 'Demosthenes junior', 'partido' => 'Agir'],
            ['id' => '35355', 'cargo_id' => '13', 'nome' => 'Denis do povo', 'partido' => 'PMB'],
            ['id' => '13777', 'cargo_id' => '13', 'nome' => 'Denise cesar', 'partido' => 'PT'],
            ['id' => '45445', 'cargo_id' => '13', 'nome' => 'Diego nabuco', 'partido' => 'PSDB'],
            ['id' => '12300', 'cargo_id' => '13', 'nome' => 'Dinardi', 'partido' => 'PDT'],
            ['id' => '22123', 'cargo_id' => '13', 'nome' => 'Dinda', 'partido' => 'PL'],
            ['id' => '12100', 'cargo_id' => '13', 'nome' => 'Diogo garçom', 'partido' => 'PDT'],
            ['id' => '44558', 'cargo_id' => '13', 'nome' => 'Dr cícero', 'partido' => 'União'],
            ['id' => '55100', 'cargo_id' => '13', 'nome' => 'Dr flavio peres', 'partido' => 'PSD'],
            ['id' => '20222', 'cargo_id' => '13', 'nome' => 'Dulci cambury', 'partido' => 'Pode'],
            ['id' => '20123', 'cargo_id' => '13', 'nome' => 'Edgar celestino', 'partido' => 'Pode'],
            ['id' => '11555', 'cargo_id' => '13', 'nome' => 'Edgar reimberg', 'partido' => 'PP'],
            ['id' => '55013', 'cargo_id' => '13', 'nome' => 'Edson cheiro', 'partido' => 'PSD'],
            ['id' => '45014', 'cargo_id' => '13', 'nome' => 'Elaine nunes', 'partido' => 'PSDB'],
            ['id' => '30007', 'cargo_id' => '13', 'nome' => 'Elizia faustino', 'partido' => 'Novo'],
            ['id' => '45500', 'cargo_id' => '13', 'nome' => 'Enfermeira maria ângela', 'partido' => 'PSDB'],
            ['id' => '22722', 'cargo_id' => '13', 'nome' => 'Engenheira raquel macena', 'partido' => 'PL'],
            ['id' => '15007', 'cargo_id' => '13', 'nome' => 'Ercílio', 'partido' => 'MDB'],
            ['id' => '11999', 'cargo_id' => '13', 'nome' => 'Ernaninho', 'partido' => 'PP'],
            ['id' => '40444', 'cargo_id' => '13', 'nome' => 'Fabi medioli', 'partido' => 'PSB'],
            ['id' => '35222', 'cargo_id' => '13', 'nome' => 'Fabio oliveira maresias brasil', 'partido' => 'PMB'],
            ['id' => '40456', 'cargo_id' => '13', 'nome' => 'Felipe cardim', 'partido' => 'PSB'],
            ['id' => '30010', 'cargo_id' => '13', 'nome' => 'Felipe moledo', 'partido' => 'Novo'],
            ['id' => '30500', 'cargo_id' => '13', 'nome' => 'Felipe zangado', 'partido' => 'Novo'],
            ['id' => '15015', 'cargo_id' => '13', 'nome' => 'Fernando faustino', 'partido' => 'MDB'],
            ['id' => '10012', 'cargo_id' => '13', 'nome' => 'Flavio morais do esporte', 'partido' => 'Republicanos'],
            ['id' => '45123', 'cargo_id' => '13', 'nome' => 'Flávio pitomba', 'partido' => 'PSDB'],
            ['id' => '55505', 'cargo_id' => '13', 'nome' => 'Gabi podologa', 'partido' => 'PSD'],
            ['id' => '15001', 'cargo_id' => '13', 'nome' => 'Gê da adega', 'partido' => 'MDB'],
            ['id' => '12900', 'cargo_id' => '13', 'nome' => 'Geraldo pipoqueiro', 'partido' => 'PDT'],
            ['id' => '40007', 'cargo_id' => '13', 'nome' => 'Gerson ge', 'partido' => 'PSB'],
            ['id' => '22001', 'cargo_id' => '13', 'nome' => 'Gil buscapé', 'partido' => 'PL'],
            ['id' => '18000', 'cargo_id' => '13', 'nome' => 'Gil psiu', 'partido' => 'Rede'],
            ['id' => '44180', 'cargo_id' => '13', 'nome' => 'Gilmário gil', 'partido' => 'União'],
            ['id' => '11000', 'cargo_id' => '13', 'nome' => 'Giovani pixoxó', 'partido' => 'PP'],
            ['id' => '36177', 'cargo_id' => '13', 'nome' => 'Glaucia do social', 'partido' => 'Agir'],
            ['id' => '18018', 'cargo_id' => '13', 'nome' => 'Gledson do bairro', 'partido' => 'Rede'],
            ['id' => '77555', 'cargo_id' => '13', 'nome' => 'Guilherme', 'partido' => 'Solidariedade'],
            ['id' => '20789', 'cargo_id' => '13', 'nome' => 'Heniel', 'partido' => 'Pode'],
            ['id' => '10111', 'cargo_id' => '13', 'nome' => 'Henriana lacerda', 'partido' => 'Republicanos'],
            ['id' => '30123', 'cargo_id' => '13', 'nome' => 'Ivan alvarenga', 'partido' => 'Novo'],
            ['id' => '36000', 'cargo_id' => '13', 'nome' => 'Ivan auto escola', 'partido' => 'Agir'],
            ['id' => '25190', 'cargo_id' => '13', 'nome' => 'Ivan do gás', 'partido' => 'PRD'],
            ['id' => '12345', 'cargo_id' => '13', 'nome' => 'Izaias jr', 'partido' => 'PDT'],
            ['id' => '25192', 'cargo_id' => '13', 'nome' => 'Janete cabeleireira', 'partido' => 'PRD'],
            ['id' => '11333', 'cargo_id' => '13', 'nome' => 'Jeferson puff', 'partido' => 'PP'],
            ['id' => '55345', 'cargo_id' => '13', 'nome' => 'Joao freitas', 'partido' => 'PSD'],
            ['id' => '30333', 'cargo_id' => '13', 'nome' => 'Joao grandão força e renovação', 'partido' => 'Novo'],
            ['id' => '11111', 'cargo_id' => '13', 'nome' => 'João paulo teixeira', 'partido' => 'PP'],
            ['id' => '77777', 'cargo_id' => '13', 'nome' => 'Jobson', 'partido' => 'Solidariedade'],
            ['id' => '18555', 'cargo_id' => '13', 'nome' => 'Joelma de bare', 'partido' => 'Rede'],
            ['id' => '15555', 'cargo_id' => '13', 'nome' => 'Jotinha', 'partido' => 'MDB'],
            ['id' => '44789', 'cargo_id' => '13', 'nome' => 'Juci franco', 'partido' => 'União'],
            ['id' => '40123', 'cargo_id' => '13', 'nome' => 'Kaka vieira', 'partido' => 'PSB'],
            ['id' => '20025', 'cargo_id' => '13', 'nome' => 'Karen do gás', 'partido' => 'Pode'],
            ['id' => '77888', 'cargo_id' => '13', 'nome' => 'Karina', 'partido' => 'Solidariedade'],
            ['id' => '55999', 'cargo_id' => '13', 'nome' => 'Karla da doceria flor de cravo', 'partido' => 'PSD'],
            ['id' => '13130', 'cargo_id' => '13', 'nome' => 'Laercio honorato', 'partido' => 'PT'],
            ['id' => '44400', 'cargo_id' => '13', 'nome' => 'Lau guimarães', 'partido' => 'União'],
            ['id' => '45777', 'cargo_id' => '13', 'nome' => 'Letícia ávila', 'partido' => 'PSDB'],
            ['id' => '13999', 'cargo_id' => '13', 'nome' => 'Levy do sindicato', 'partido' => 'PT'],
            ['id' => '35555', 'cargo_id' => '13', 'nome' => 'Levy santos', 'partido' => 'PMB'],
            ['id' => '25123', 'cargo_id' => '13', 'nome' => 'Lidia', 'partido' => 'PRD'],
            ['id' => '35111', 'cargo_id' => '13', 'nome' => 'Luana silva', 'partido' => 'PMB'],
            ['id' => '30030', 'cargo_id' => '13', 'nome' => 'Luciana amaral', 'partido' => 'Novo'],
            ['id' => '55001', 'cargo_id' => '13', 'nome' => 'Luciane bissacot', 'partido' => 'PSD'],
            ['id' => '35007', 'cargo_id' => '13', 'nome' => 'Luciano simpatia', 'partido' => 'PMB'],
            ['id' => '15192', 'cargo_id' => '13', 'nome' => 'Luís da saúde', 'partido' => 'MDB'],
            ['id' => '50000', 'cargo_id' => '13', 'nome' => 'Luiz arquiteto', 'partido' => 'PSOL'],
            ['id' => '18008', 'cargo_id' => '13', 'nome' => 'Luizão cabra forte', 'partido' => 'Rede'],
            ['id' => '77999', 'cargo_id' => '13', 'nome' => 'Macarrão', 'partido' => 'Solidariedade'],
            ['id' => '44777', 'cargo_id' => '13', 'nome' => 'Marcão iapoi', 'partido' => 'União'],
            ['id' => '10005', 'cargo_id' => '13', 'nome' => 'Marcelo maresias', 'partido' => 'Republicanos'],
            ['id' => '12512', 'cargo_id' => '13', 'nome' => 'Márcia januario', 'partido' => 'PDT'],
            ['id' => '55000', 'cargo_id' => '13', 'nome' => 'Marcos brasil', 'partido' => 'PSD'],
            ['id' => '44544', 'cargo_id' => '13', 'nome' => 'Marcos fuly', 'partido' => 'União'],
            ['id' => '12888', 'cargo_id' => '13', 'nome' => 'Maria fernanda', 'partido' => 'PDT'],
            ['id' => '45444', 'cargo_id' => '13', 'nome' => 'Maria magdalena draxler damazi', 'partido' => 'PSDB'],
            ['id' => '11777', 'cargo_id' => '13', 'nome' => 'Marinho da habitação', 'partido' => 'PP'],
            ['id' => '12500', 'cargo_id' => '13', 'nome' => 'Marise cabeleireira', 'partido' => 'PDT'],
            ['id' => '44380', 'cargo_id' => '13', 'nome' => 'Marquinhos da sabesp', 'partido' => 'União'],
            ['id' => '36321', 'cargo_id' => '13', 'nome' => 'Marrom do som', 'partido' => 'Agir'],
            ['id' => '22022', 'cargo_id' => '13', 'nome' => 'Mauricio da feira', 'partido' => 'PL'],
            ['id' => '10000', 'cargo_id' => '13', 'nome' => 'Mauricio do canto do mar', 'partido' => 'Republicanos'],
            ['id' => '36566', 'cargo_id' => '13', 'nome' => 'Mestre carvoeiro', 'partido' => 'Agir'],
            ['id' => '13123', 'cargo_id' => '13', 'nome' => 'Mestre tubarão', 'partido' => 'PT'],
            ['id' => '65000', 'cargo_id' => '13', 'nome' => 'Mestre val', 'partido' => 'PC do B'],
            ['id' => '36123', 'cargo_id' => '13', 'nome' => 'Mika lomeu', 'partido' => 'Agir'],
            ['id' => '15190', 'cargo_id' => '13', 'nome' => 'Andréia', 'partido' => 'MDB'],
            ['id' => '10555', 'cargo_id' => '13', 'nome' => 'Murilo maresias', 'partido' => 'Republicanos'],
            ['id' => '44444', 'cargo_id' => '13', 'nome' => 'Nathi pacheco', 'partido' => 'União'],
            ['id' => '10321', 'cargo_id' => '13', 'nome' => 'Nathiele santana', 'partido' => 'Republicanos'],
            ['id' => '25678', 'cargo_id' => '13', 'nome' => 'Nathy juquehy', 'partido' => 'PRD'],
            ['id' => '25005', 'cargo_id' => '13', 'nome' => 'Neidinha maresias', 'partido' => 'PRD'],
            ['id' => '36555', 'cargo_id' => '13', 'nome' => 'Nelson artista', 'partido' => 'Agir'],
            ['id' => '20200', 'cargo_id' => '13', 'nome' => 'Niuara', 'partido' => 'Pode'],
            ['id' => '13111', 'cargo_id' => '13', 'nome' => 'Ozama', 'partido' => 'PT'],
            ['id' => '11321', 'cargo_id' => '13', 'nome' => 'Pardal', 'partido' => 'PP'],
            ['id' => '30555', 'cargo_id' => '13', 'nome' => 'Pastor adãozinho', 'partido' => 'Novo'],
            ['id' => '55777', 'cargo_id' => '13', 'nome' => 'Pastor diego marques', 'partido' => 'PSD'],
            ['id' => '20777', 'cargo_id' => '13', 'nome' => 'Pastor elias de madureira', 'partido' => 'Pode'],
            ['id' => '10001', 'cargo_id' => '13', 'nome' => 'Pastor gil', 'partido' => 'Republicanos'],
            ['id' => '44321', 'cargo_id' => '13', 'nome' => 'Pastor jessé borges', 'partido' => 'União'],
            ['id' => '77000', 'cargo_id' => '13', 'nome' => 'Patricia', 'partido' => 'Solidariedade'],
            ['id' => '33456', 'cargo_id' => '13', 'nome' => 'Patricia braga', 'partido' => 'Mobiliza'],
            ['id' => '35000', 'cargo_id' => '13', 'nome' => 'Patropi a voz do povo', 'partido' => 'PMB'],
            ['id' => '45222', 'cargo_id' => '13', 'nome' => 'Patu', 'partido' => 'PSDB'],
            ['id' => '45007', 'cargo_id' => '13', 'nome' => 'Paulinho do cartório', 'partido' => 'PSDB'],
            ['id' => '13456', 'cargo_id' => '13', 'nome' => 'Paulinho do telhado', 'partido' => 'PT'],
            ['id' => '25025', 'cargo_id' => '13', 'nome' => 'Pedrinho oliveira', 'partido' => 'PRD'],
            ['id' => '40777', 'cargo_id' => '13', 'nome' => 'Pedro da farmacia', 'partido' => 'PSB'],
            ['id' => '45000', 'cargo_id' => '13', 'nome' => 'Ph', 'partido' => 'PSDB'],
            ['id' => '25222', 'cargo_id' => '13', 'nome' => 'Piva', 'partido' => 'PRD'],
            ['id' => '55010', 'cargo_id' => '13', 'nome' => 'Prof janaina borin', 'partido' => 'PSD'],
            ['id' => '55678', 'cargo_id' => '13', 'nome' => 'Prof paulo ivo', 'partido' => 'PSD'],
            ['id' => '77890', 'cargo_id' => '13', 'nome' => 'Prof tiago', 'partido' => 'Solidariedade'],
            ['id' => '35123', 'cargo_id' => '13', 'nome' => 'Prof. daniel proença', 'partido' => 'PMB'],
            ['id' => '15012', 'cargo_id' => '13', 'nome' => 'Prof. diego serena', 'partido' => 'MDB'],
            ['id' => '44000', 'cargo_id' => '13', 'nome' => 'Prof. valdécio', 'partido' => 'União'],
            ['id' => '10456', 'cargo_id' => '13', 'nome' => 'Professor alex damasceno', 'partido' => 'Republicanos'],
            ['id' => '45045', 'cargo_id' => '13', 'nome' => 'Professor cardim', 'partido' => 'PSDB'],
            ['id' => '20333', 'cargo_id' => '13', 'nome' => 'Professor glauber', 'partido' => 'Pode'],
            ['id' => '13333', 'cargo_id' => '13', 'nome' => 'Professora adriana', 'partido' => 'PT'],
            ['id' => '10777', 'cargo_id' => '13', 'nome' => 'Professora carla', 'partido' => 'Republicanos'],
            ['id' => '30300', 'cargo_id' => '13', 'nome' => 'Professora ciça', 'partido' => 'Novo'],
            ['id' => '22218', 'cargo_id' => '13', 'nome' => 'Professora cristina', 'partido' => 'PL'],
            ['id' => '15051', 'cargo_id' => '13', 'nome' => 'Professora leda', 'partido' => 'MDB'],
            ['id' => '77222', 'cargo_id' => '13', 'nome' => 'Professora lú', 'partido' => 'Solidariedade'],
            ['id' => '12700', 'cargo_id' => '13', 'nome' => 'Professora maria helena', 'partido' => 'PDT'],
            ['id' => '43111', 'cargo_id' => '13', 'nome' => 'Professora rosinéa garçon', 'partido' => 'PV'],
            ['id' => '18999', 'cargo_id' => '13', 'nome' => 'Puff alves', 'partido' => 'Rede'],
            ['id' => '22777', 'cargo_id' => '13', 'nome' => 'Alfredo do Valle', 'partido' => 'PL'],
            ['id' => '15333', 'cargo_id' => '13', 'nome' => 'Rai sousa', 'partido' => 'MDB'],
            ['id' => '36337', 'cargo_id' => '13', 'nome' => 'Raquel luna', 'partido' => 'Agir'],
            ['id' => '18222', 'cargo_id' => '13', 'nome' => 'Ray cury', 'partido' => 'Rede'],
            ['id' => '18888', 'cargo_id' => '13', 'nome' => 'Regina carvalho', 'partido' => 'Rede'],
            ['id' => '12222', 'cargo_id' => '13', 'nome' => 'Renan santos', 'partido' => 'PDT'],
            ['id' => '35888', 'cargo_id' => '13', 'nome' => 'Renata gabriela', 'partido' => 'PMB'],
            ['id' => '45333', 'cargo_id' => '13', 'nome' => 'Renato', 'partido' => 'PSDB'],
            ['id' => '25250', 'cargo_id' => '13', 'nome' => 'Rene da causa animal', 'partido' => 'PRD'],
            ['id' => '35001', 'cargo_id' => '13', 'nome' => 'Roberto brito', 'partido' => 'PMB'],
            ['id' => '15222', 'cargo_id' => '13', 'nome' => 'Robson do samu', 'partido' => 'MDB'],
            ['id' => '22222', 'cargo_id' => '13', 'nome' => 'Rodrigo caldeira', 'partido' => 'PL'],
            ['id' => '35010', 'cargo_id' => '13', 'nome' => 'Ronaldo farmaceutico', 'partido' => 'PMB'],
            ['id' => '35005', 'cargo_id' => '13', 'nome' => 'Rose do pedal', 'partido' => 'PMB'],
            ['id' => '10220', 'cargo_id' => '13', 'nome' => 'Rosinei ribeiro', 'partido' => 'Republicanos'],
            ['id' => '65123', 'cargo_id' => '13', 'nome' => 'Sabrina morais caiçara', 'partido' => 'PC do B'],
            ['id' => '18188', 'cargo_id' => '13', 'nome' => 'Selminha', 'partido' => 'Rede'],
            ['id' => '30777', 'cargo_id' => '13', 'nome' => 'Sivaldo chaveiro', 'partido' => 'Novo'],
            ['id' => '36099', 'cargo_id' => '13', 'nome' => 'Solange matos', 'partido' => 'Agir'],
            ['id' => '22622', 'cargo_id' => '13', 'nome' => 'Sombra do pastel', 'partido' => 'PL'],
            ['id' => '70000', 'cargo_id' => '13', 'nome' => 'Tarcizio da saúde', 'partido' => 'Avante'],
            ['id' => '20111', 'cargo_id' => '13', 'nome' => 'Tati muniz', 'partido' => 'Pode'],
            ['id' => '15123', 'cargo_id' => '13', 'nome' => 'Tati viola', 'partido' => 'MDB'],
            ['id' => '40000', 'cargo_id' => '13', 'nome' => 'Teimoso', 'partido' => 'PSB'],
            ['id' => '45555', 'cargo_id' => '13', 'nome' => 'Thiago baly', 'partido' => 'PSDB'],
            ['id' => '20007', 'cargo_id' => '13', 'nome' => 'Tião da solange', 'partido' => 'Pode'],
            ['id' => '15999', 'cargo_id' => '13', 'nome' => 'Tico são sebá', 'partido' => 'MDB'],
            ['id' => '55015', 'cargo_id' => '13', 'nome' => 'Tonho ivo', 'partido' => 'PSD'],
            ['id' => '13113', 'cargo_id' => '13', 'nome' => 'Tulio parodi', 'partido' => 'PT'],
            ['id' => '10010', 'cargo_id' => '13', 'nome' => 'Valdir teixeira', 'partido' => 'Republicanos'],
            ['id' => '11444', 'cargo_id' => '13', 'nome' => 'Valquiria barroso', 'partido' => 'PP'],
            ['id' => '44212', 'cargo_id' => '13', 'nome' => 'Vânia cavalcante', 'partido' => 'União'],
            ['id' => '25003', 'cargo_id' => '13', 'nome' => 'Vanilson do itatinga', 'partido' => 'PRD'],
            ['id' => '70111', 'cargo_id' => '13', 'nome' => 'Vilma do bolo', 'partido' => 'Avante'],
            ['id' => '25000', 'cargo_id' => '13', 'nome' => 'Vitor freire de oliveira', 'partido' => 'PRD'],
            ['id' => '22000', 'cargo_id' => '13', 'nome' => 'Vivi paiva', 'partido' => 'PL'],
            ['id' => '44001', 'cargo_id' => '13', 'nome' => 'Wagner teixeira', 'partido' => 'União'],
            ['id' => '40199', 'cargo_id' => '13', 'nome' => 'Waguinho', 'partido' => 'PSB'],
            ['id' => '30000', 'cargo_id' => '13', 'nome' => 'Wanderley rodrigues', 'partido' => 'Novo'],
            ['id' => '45633', 'cargo_id' => '13', 'nome' => 'Wellington bilicão', 'partido' => 'PSDB'],
            ['id' => '35777', 'cargo_id' => '13', 'nome' => 'Will lira', 'partido' => 'PMB'],
            ['id' => '20444', 'cargo_id' => '13', 'nome' => 'Zezé do iate', 'partido' => 'Pode'],
            ['id' => '12670', 'cargo_id' => '13', 'nome' => 'Zezinho da piscina', 'partido' => 'PDT'],
            ['id' => '30699', 'cargo_id' => '13', 'nome' => 'Pr antônio carlos', 'partido' => 'Novo'],
            ['id' => '11007', 'cargo_id' => '13', 'nome' => 'Karina insaurrade', 'partido' => 'PP'],
            ['id' => '33100', 'cargo_id' => '13', 'nome' => 'Adson Silva', 'partido' => 'Mobiliza'],
        ]);
    }
}
