<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CandidatoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('candidatos')->insert([
            ['id' => '55', 'nome' => 'dr juan garcia', 'cargo_id' => '11'],
            ['id' => '77', 'nome' => 'dr nil', 'cargo_id' => '11'],
            ['id' => '11', 'nome' => 'professor gleivison', 'cargo_id' => '11'],
            ['id' => '10', 'nome' => 'reinaldinho', 'cargo_id' => '11'],
            ['id' => '21', 'nome' => 'vinicius mandato coletivo pcb', 'cargo_id' => '11'],
            ['id' => '55555', 'nome' => 'abel gama', 'cargo_id' => '13'],
            ['id' => '22111', 'nome' => 'abidias', 'cargo_id' => '13'],
            ['id' => '36500', 'nome' => 'adeildo toque toque', 'cargo_id' => '13'],
            ['id' => '33100', 'nome' => 'adson silva', 'cargo_id' => '13'],
            ['id' => '22333', 'nome' => 'ailson do flutuante', 'cargo_id' => '13'],
            ['id' => '18123', 'nome' => 'alberto mendes', 'cargo_id' => '13'],
            ['id' => '55055', 'nome' => 'alceu moura', 'cargo_id' => '13'],
            ['id' => '40222', 'nome' => 'alessandro negó', 'cargo_id' => '13'],
            ['id' => '10211', 'nome' => 'alicate', 'cargo_id' => '13'],
            ['id' => '36125', 'nome' => 'amancio papai noel', 'cargo_id' => '13'],
            ['id' => '40333', 'nome' => 'amanda bombeira civil', 'cargo_id' => '13'],
            ['id' => '35003', 'nome' => 'amelia', 'cargo_id' => '13'],
            ['id' => '11600', 'nome' => 'amilton pacheco', 'cargo_id' => '13'],
            ['id' => '77123', 'nome' => 'anderson gandra', 'cargo_id' => '13'],
            ['id' => '20000', 'nome' => 'andre pierobon', 'cargo_id' => '13'],
            ['id' => '11222', 'nome' => 'angélica cassanho', 'cargo_id' => '13'],
            ['id' => '33111', 'nome' => 'animal', 'cargo_id' => '13'],
            ['id' => '11888', 'nome' => 'anne faria', 'cargo_id' => '13'],
            ['id' => '20555', 'nome' => 'arquimedes', 'cargo_id' => '13'],
            ['id' => '20800', 'nome' => 'ary junior', 'cargo_id' => '13'],
            ['id' => '40111', 'nome' => 'balbino', 'cargo_id' => '13'],
            ['id' => '18137', 'nome' => 'barão nobre', 'cargo_id' => '13'],
            ['id' => '36036', 'nome' => 'baratinha', 'cargo_id' => '13'],
            ['id' => '45633', 'nome' => 'belicão', 'cargo_id' => '13'],
            ['id' => '25193', 'nome' => 'bibi bombeiro', 'cargo_id' => '13'],
            ['id' => '77007', 'nome' => 'boni', 'cargo_id' => '13'],
            ['id' => '30321', 'nome' => 'brodinho', 'cargo_id' => '13'],
            ['id' => '15000', 'nome' => 'caboclo', 'cargo_id' => '13'],
            ['id' => '43333', 'nome' => 'cacique guarani', 'cargo_id' => '13'],
            ['id' => '13000', 'nome' => 'camila aquino', 'cargo_id' => '13'],
            ['id' => '44123', 'nome' => 'camila tereza', 'cargo_id' => '13'],
            ['id' => '12123', 'nome' => 'capitão wellington', 'cargo_id' => '13'],
            ['id' => '18678', 'nome' => 'chico macarrão', 'cargo_id' => '13'],
            ['id' => '40213', 'nome' => 'cida paraiba', 'cargo_id' => '13'],
            ['id' => '70222', 'nome' => 'cida pauba', 'cargo_id' => '13'],
            ['id' => '22224', 'nome' => 'claudinha maresias', 'cargo_id' => '13'],
            ['id' => '12000', 'nome' => 'claudinho do trânsito', 'cargo_id' => '13'],
            ['id' => '12800', 'nome' => 'claudio taxista', 'cargo_id' => '13'],
            ['id' => '25010', 'nome' => 'coio', 'cargo_id' => '13'],
            ['id' => '22212', 'nome' => 'comandante sergio ramos', 'cargo_id' => '13'],
            ['id' => '50123', 'nome' => 'cristiane maria', 'cargo_id' => '13'],
            ['id' => '40112', 'nome' => 'dani kihara', 'cargo_id' => '13'],
            ['id' => '25244', 'nome' => 'daniel do morro', 'cargo_id' => '13'],
            ['id' => '11123', 'nome' => 'daniel simões', 'cargo_id' => '13'],
            ['id' => '10123', 'nome' => 'daniel soares', 'cargo_id' => '13'],
            ['id' => '30222', 'nome' => 'danúbia da integra', 'cargo_id' => '13'],
            ['id' => '30001', 'nome' => 'david nascimento', 'cargo_id' => '13'],
            ['id' => '40640', 'nome' => 'dedinho', 'cargo_id' => '13'],
            ['id' => '36777', 'nome' => 'demosthenes junior', 'cargo_id' => '13'],
            ['id' => '35355', 'nome' => 'denis do povo', 'cargo_id' => '13'],
            ['id' => '13777', 'nome' => 'denise cesar', 'cargo_id' => '13'],
            ['id' => '45445', 'nome' => 'diego nabuco', 'cargo_id' => '13'],
            ['id' => '12300', 'nome' => 'dinardi', 'cargo_id' => '13'],
            ['id' => '22123', 'nome' => 'dinda', 'cargo_id' => '13'],
            ['id' => '12100', 'nome' => 'diogo garçom', 'cargo_id' => '13'],
            ['id' => '44558', 'nome' => 'dr cícero', 'cargo_id' => '13'],
            ['id' => '55100', 'nome' => 'dr flavio peres', 'cargo_id' => '13'],
            ['id' => '20222', 'nome' => 'dulci cambury', 'cargo_id' => '13'],
            ['id' => '20123', 'nome' => 'edgar celestino', 'cargo_id' => '13'],
            ['id' => '11555', 'nome' => 'edgar reimberg', 'cargo_id' => '13'],
            ['id' => '55013', 'nome' => 'edson cheiro', 'cargo_id' => '13'],
            ['id' => '45014', 'nome' => 'elaine nunes', 'cargo_id' => '13'],
            ['id' => '30007', 'nome' => 'elizia faustino', 'cargo_id' => '13'],
            ['id' => '15007', 'nome' => 'ercílio', 'cargo_id' => '13'],
            ['id' => '11999', 'nome' => 'ernaninho', 'cargo_id' => '13'],
            ['id' => '40444', 'nome' => 'fabi medioli', 'cargo_id' => '13'],
            ['id' => '35222', 'nome' => 'fabio oliveira maresias brasil', 'cargo_id' => '13'],
            ['id' => '40456', 'nome' => 'felipe cardim', 'cargo_id' => '13'],
            ['id' => '30500', 'nome' => 'felipe zangado', 'cargo_id' => '13'],
            ['id' => '15015', 'nome' => 'fernando faustino', 'cargo_id' => '13'],
            ['id' => '10012', 'nome' => 'flavio morais do esporte', 'cargo_id' => '13'],
            ['id' => '55505', 'nome' => 'gabi podologa', 'cargo_id' => '13'],
            ['id' => '15001', 'nome' => 'gê da adega', 'cargo_id' => '13'],
            ['id' => '12900', 'nome' => 'geraldo pipoqueiro', 'cargo_id' => '13'],
            ['id' => '40007', 'nome' => 'gerson ge', 'cargo_id' => '13'],
            ['id' => '22001', 'nome' => 'gil buscapé', 'cargo_id' => '13'],
            ['id' => '18000', 'nome' => 'gil psiu', 'cargo_id' => '13'],
            ['id' => '44180', 'nome' => 'gilmário gil', 'cargo_id' => '13'],
            ['id' => '11000', 'nome' => 'giovani pixoxó', 'cargo_id' => '13'],
            ['id' => '36177', 'nome' => 'glaucia do social', 'cargo_id' => '13'],
            ['id' => '18018', 'nome' => 'gledson do bairro', 'cargo_id' => '13'],
            ['id' => '77555', 'nome' => 'guilherme', 'cargo_id' => '13'],
            ['id' => '20789', 'nome' => 'heniel', 'cargo_id' => '13'],
            ['id' => '10111', 'nome' => 'henriana lacerda', 'cargo_id' => '13'],
            ['id' => '30123', 'nome' => 'ivan alvarenga', 'cargo_id' => '13'],
            ['id' => '36000', 'nome' => 'ivan auto escola', 'cargo_id' => '13'],
            ['id' => '25190', 'nome' => 'ivan do gás', 'cargo_id' => '13'],
            ['id' => '12345', 'nome' => 'izaias jr', 'cargo_id' => '13'],
            ['id' => '25192', 'nome' => 'janete cabeleireira', 'cargo_id' => '13'],
            ['id' => '11333', 'nome' => 'jeferson puff', 'cargo_id' => '13'],
            ['id' => '55345', 'nome' => 'joao freitas', 'cargo_id' => '13'],
            ['id' => '30333', 'nome' => 'joao grandão força e renovação', 'cargo_id' => '13'],
            ['id' => '11111', 'nome' => 'joão paulo teixeira', 'cargo_id' => '13'],
            ['id' => '77777', 'nome' => 'jobson', 'cargo_id' => '13'],
            ['id' => '18555', 'nome' => 'joelma de bare', 'cargo_id' => '13'],
            ['id' => '15555', 'nome' => 'jotinha', 'cargo_id' => '13'],
            ['id' => '44789', 'nome' => 'juci franco', 'cargo_id' => '13'],
            ['id' => '40123', 'nome' => 'kaka vieira', 'cargo_id' => '13'],
            ['id' => '20025', 'nome' => 'karen do gás', 'cargo_id' => '13'],
            ['id' => '77888', 'nome' => 'karina', 'cargo_id' => '13'],
            ['id' => '11007', 'nome' => 'karina insaurrade', 'cargo_id' => '13'],
            ['id' => '55999', 'nome' => 'karla da doceria flor de cravo', 'cargo_id' => '13'],
            ['id' => '13130', 'nome' => 'laercio honorato', 'cargo_id' => '13'],
            ['id' => '44400', 'nome' => 'lau guimarães', 'cargo_id' => '13'],
            ['id' => '13999', 'nome' => 'levy do sindicato', 'cargo_id' => '13'],
            ['id' => '35555', 'nome' => 'levy santos', 'cargo_id' => '13'],
            ['id' => '25123', 'nome' => 'lidia', 'cargo_id' => '13'],
            ['id' => '35111', 'nome' => 'luana silva', 'cargo_id' => '13'],
            ['id' => '30030', 'nome' => 'luciana amaral', 'cargo_id' => '13'],
            ['id' => '55001', 'nome' => 'luciane bissacot', 'cargo_id' => '13'],
            ['id' => '35007', 'nome' => 'luciano simpatia', 'cargo_id' => '13'],
            ['id' => '15192', 'nome' => 'luís da saúde', 'cargo_id' => '13'],
            ['id' => '50000', 'nome' => 'luiz arquiteto', 'cargo_id' => '13'],
            ['id' => '18008', 'nome' => 'luizão cabra forte', 'cargo_id' => '13'],
            ['id' => '77999', 'nome' => 'macarrão', 'cargo_id' => '13'],
            ['id' => '44777', 'nome' => 'marcão iapoi', 'cargo_id' => '13'],
            ['id' => '10005', 'nome' => 'marcelo maresias', 'cargo_id' => '13'],
            ['id' => '12512', 'nome' => 'marcia januaria', 'cargo_id' => '13'],
            ['id' => '55000', 'nome' => 'marcos brasil', 'cargo_id' => '13'],
            ['id' => '44544', 'nome' => 'marcos fuly', 'cargo_id' => '13'],
            ['id' => '45500', 'nome' => 'maria angela', 'cargo_id' => '13'],
            ['id' => '12888', 'nome' => 'maria fernanda', 'cargo_id' => '13'],
            ['id' => '11777', 'nome' => 'marinho da habitação', 'cargo_id' => '13'],
            ['id' => '12500', 'nome' => 'marise cabeleireira', 'cargo_id' => '13'],
            ['id' => '44380', 'nome' => 'marquinhos da sabesp', 'cargo_id' => '13'],
            ['id' => '36321', 'nome' => 'marrom do som', 'cargo_id' => '13'],
            ['id' => '22022', 'nome' => 'mauricio da feira', 'cargo_id' => '13'],
            ['id' => '10000', 'nome' => 'mauricio do canto do mar', 'cargo_id' => '13'],
            ['id' => '36566', 'nome' => 'mestre carvoeiro', 'cargo_id' => '13'],
            ['id' => '13123', 'nome' => 'mestre tubarão', 'cargo_id' => '13'],
            ['id' => '65000', 'nome' => 'mestre val', 'cargo_id' => '13'],
            ['id' => '36123', 'nome' => 'mika lomeu', 'cargo_id' => '13'],
            ['id' => '15190', 'nome' => 'monique camilo', 'cargo_id' => '13'],
            ['id' => '10555', 'nome' => 'murilo maresias', 'cargo_id' => '13'],
            ['id' => '44444', 'nome' => 'nathi pacheco', 'cargo_id' => '13'],
            ['id' => '10321', 'nome' => 'nathiele santana', 'cargo_id' => '13'],
            ['id' => '25678', 'nome' => 'nathy juquehy', 'cargo_id' => '13'],
            ['id' => '25005', 'nome' => 'neidinha maresias', 'cargo_id' => '13'],
            ['id' => '36555', 'nome' => 'nelson artista', 'cargo_id' => '13'],
            ['id' => '20200', 'nome' => 'niuara', 'cargo_id' => '13'],
            ['id' => '13111', 'nome' => 'ozama', 'cargo_id' => '13'],
            ['id' => '11321', 'nome' => 'pardal', 'cargo_id' => '13'],
            ['id' => '30555', 'nome' => 'pastor adãozinho', 'cargo_id' => '13'],
            ['id' => '55777', 'nome' => 'pastor diego marques', 'cargo_id' => '13'],
            ['id' => '20777', 'nome' => 'pastor elias', 'cargo_id' => '13'],
            ['id' => '10001', 'nome' => 'pastor gil', 'cargo_id' => '13'],
            ['id' => '44321', 'nome' => 'pastor jessé borges', 'cargo_id' => '13'],
            ['id' => '45777', 'nome' => 'pastora leticia', 'cargo_id' => '13'],
            ['id' => '33456', 'nome' => 'patricia', 'cargo_id' => '13'],
            ['id' => '77000', 'nome' => 'patricia', 'cargo_id' => '13'],
            ['id' => '35000', 'nome' => 'patropi a voz do povo', 'cargo_id' => '13'],
            ['id' => '45222', 'nome' => 'patu', 'cargo_id' => '13'],
            ['id' => '45007', 'nome' => 'paulinho do cartório', 'cargo_id' => '13'],
            ['id' => '13456', 'nome' => 'paulinho do telhado', 'cargo_id' => '13'],
            ['id' => '25025', 'nome' => 'pedrinho oliveira', 'cargo_id' => '13'],
            ['id' => '40777', 'nome' => 'pedro da farmacia', 'cargo_id' => '13'],
            ['id' => '45000', 'nome' => 'ph', 'cargo_id' => '13'],
            ['id' => '45123', 'nome' => 'pitomba', 'cargo_id' => '13'],
            ['id' => '25222', 'nome' => 'piva', 'cargo_id' => '13'],
            ['id' => '30699', 'nome' => 'pr antônio carlos', 'cargo_id' => '13'],
            ['id' => '45045', 'nome' => 'prof cardim', 'cargo_id' => '13'],
            ['id' => '55010', 'nome' => 'prof janaina borin', 'cargo_id' => '13'],
            ['id' => '55678', 'nome' => 'prof paulo ivo', 'cargo_id' => '13'],
            ['id' => '77890', 'nome' => 'prof tiago', 'cargo_id' => '13'],
            ['id' => '35123', 'nome' => 'prof. daniel proença', 'cargo_id' => '13'],
            ['id' => '15012', 'nome' => 'prof. diego serena', 'cargo_id' => '13'],
            ['id' => '44000', 'nome' => 'prof. valdécio', 'cargo_id' => '13'],
            ['id' => '10456', 'nome' => 'professor alex damasceno', 'cargo_id' => '13'],
            ['id' => '20333', 'nome' => 'professor glauber', 'cargo_id' => '13'],
            ['id' => '13333', 'nome' => 'professora adriana', 'cargo_id' => '13'],
            ['id' => '10777', 'nome' => 'professora carla', 'cargo_id' => '13'],
            ['id' => '30300', 'nome' => 'professora ciça', 'cargo_id' => '13'],
            ['id' => '22218', 'nome' => 'professora cristina', 'cargo_id' => '13'],
            ['id' => '15051', 'nome' => 'professora leda', 'cargo_id' => '13'],
            ['id' => '77222', 'nome' => 'professora lú', 'cargo_id' => '13'],
            ['id' => '12700', 'nome' => 'professora maria helena', 'cargo_id' => '13'],
            ['id' => '43111', 'nome' => 'professora rosinéa garçon', 'cargo_id' => '13'],
            ['id' => '18999', 'nome' => 'puff alves', 'cargo_id' => '13'],
            ['id' => '22777', 'nome' => 'rafael rittiele', 'cargo_id' => '13'],
            ['id' => '15333', 'nome' => 'rai sousa', 'cargo_id' => '13'],
            ['id' => '36337', 'nome' => 'raquel luna', 'cargo_id' => '13'],
            ['id' => '22722', 'nome' => 'raquel macena', 'cargo_id' => '13'],
            ['id' => '18222', 'nome' => 'ray cury', 'cargo_id' => '13'],
            ['id' => '18888', 'nome' => 'regina carvalho', 'cargo_id' => '13'],
            ['id' => '12222', 'nome' => 'renan santos', 'cargo_id' => '13'],
            ['id' => '35888', 'nome' => 'renata gabriela', 'cargo_id' => '13'],
            ['id' => '45333', 'nome' => 'renato', 'cargo_id' => '13'],
            ['id' => '25250', 'nome' => 'rene da causa animal', 'cargo_id' => '13'],
            ['id' => '35001', 'nome' => 'roberto brito', 'cargo_id' => '13'],
            ['id' => '15222', 'nome' => 'robson do samu', 'cargo_id' => '13'],
            ['id' => '22222', 'nome' => 'rodrigo caldeira', 'cargo_id' => '13'],
            ['id' => '35010', 'nome' => 'ronaldo farmaceutico', 'cargo_id' => '13'],
            ['id' => '35005', 'nome' => 'rose do pedal', 'cargo_id' => '13'],
            ['id' => '10220', 'nome' => 'rosinei ribeiro', 'cargo_id' => '13'],
            ['id' => '65123', 'nome' => 'sabrina morais caiçara', 'cargo_id' => '13'],
            ['id' => '18188', 'nome' => 'selminha', 'cargo_id' => '13'],
            ['id' => '30777', 'nome' => 'sivaldo chaveiro', 'cargo_id' => '13'],
            ['id' => '36099', 'nome' => 'solange matos', 'cargo_id' => '13'],
            ['id' => '22622', 'nome' => 'sombra do pastel', 'cargo_id' => '13'],
            ['id' => '70000', 'nome' => 'tarcizio da saúde', 'cargo_id' => '13'],
            ['id' => '20111', 'nome' => 'tati muniz', 'cargo_id' => '13'],
            ['id' => '15123', 'nome' => 'tati viola', 'cargo_id' => '13'],
            ['id' => '40000', 'nome' => 'teimoso', 'cargo_id' => '13'],
            ['id' => '45444', 'nome' => 'thainara pinheiro', 'cargo_id' => '13'],
            ['id' => '45555', 'nome' => 'thiago baly', 'cargo_id' => '13'],
            ['id' => '20007', 'nome' => 'tiao da solange', 'cargo_id' => '13'],
            ['id' => '15999', 'nome' => 'tico são sebá', 'cargo_id' => '13'],
            ['id' => '55015', 'nome' => 'tonho ivo', 'cargo_id' => '13'],
            ['id' => '13113', 'nome' => 'tulio parodi', 'cargo_id' => '13'],
            ['id' => '10010', 'nome' => 'valdir teixeira', 'cargo_id' => '13'],
            ['id' => '11444', 'nome' => 'valquiria barroso', 'cargo_id' => '13'],
            ['id' => '44212', 'nome' => 'vânia cavalcante', 'cargo_id' => '13'],
            ['id' => '25003', 'nome' => 'vanilson do itatinga', 'cargo_id' => '13'],
            ['id' => '70111', 'nome' => 'vilma do bolo', 'cargo_id' => '13'],
            ['id' => '25000', 'nome' => 'vitor freire de oliveira', 'cargo_id' => '13'],
            ['id' => '22000', 'nome' => 'vivi paiva', 'cargo_id' => '13'],
            ['id' => '44001', 'nome' => 'wagner teixeira', 'cargo_id' => '13'],
            ['id' => '40199', 'nome' => 'waguinho', 'cargo_id' => '13'],
            ['id' => '30000', 'nome' => 'wanderley rodrigues', 'cargo_id' => '13'],
            ['id' => '35777', 'nome' => 'will lira', 'cargo_id' => '13'],
            ['id' => '20444', 'nome' => 'zeze de barra do una', 'cargo_id' => '13'],
            ['id' => '12670', 'nome' => 'zezinho da piscina', 'cargo_id' => '13'],
        ]);
    }
}
